### ISSUE TITLE
Update instance details

### ISSUE THREAD

**Issue by r2fo** [Metastem/wikiless#101]
I run an instance at https://wikiless.r4fo.com and now also at http://wikiless.r4focoma7gu2zdwwcjjad47ysxt634lg73sxmdbkdozanwqslho5ohyd.onion.

For privacy improvements, I have disabled Cloudflare proxying. Can you please edit the list?

**Comment by xbdmHQ** [comment]
> I run an instance at https://wikiless.r4fo.com and now also at http://wikiless.r4focoma7gu2zdwwcjjad47ysxt634lg73sxmdbkdozanwqslho5ohyd.onion.
> 
> For privacy improvements, I have disabled Cloudflare proxying. Can you please edit the list?

Done
