### ISSUE TITLE
Most wiki links don't work when clicked in a wikiless page

### ISSUE THREAD

**Issue by ColossusChang** [Metastem/Wikiless#105]
For example, clicking on the Wikiless logo directs me to `https://wikiless.lunar.icu/Main_Page?lang=en`, which shows `Cannot GET /Main_Page`. The correct url should be `https://wikiless.lunar.icu/wiki/Main_Page?lang=en`. The `/wiki/` is missing in all wiki links except for switching languages. 

Using instance `https://wikiless.lunar.icu/`.

**Comment by 0x09AF** [comment]
Same here on the latest container image, private instance

**Comment by AlexPewMaster** [comment]
This is also happening on my instance. Whenever I want to navigate through Wikiless itself, I manually have to enter `/wiki/` in the URL bar to get a proper page.

**Comment by blade10101** [comment]
I don't think the dev is working on this any more

**Comment by xbdmHQ** [comment]
> I don't think the dev is working on this any more

The instance owner didn't set it up property, so another instance instead:

https://github.com/Metastem/wikiless/wiki/Instances

**Comment by teishahbc** [comment]
I used the prebuild docker image and got the same problem, anyone knows how to fix it?

**Comment by Morethanevil** [comment]
Same problem with the latest image, even if I build it :(
