### ISSUE TITLE
Add wikiless instance - https://wiki.nerdvpn.de

### ISSUE THREAD

**Issue by Sommerwiesel** [Metastem/wikiless#110]
URL: https://wiki.nerdvpn.de
Hoster: Virtual Systems LLC (vsys.host)
Location: Ukraine
MITM: No
Bot protection: Yes, server-side, no info is shared with third parties
Uptime monitor: [Updown.io](https://updown.io/stv1)
Server: Dedicated, 2 Gbps Unlimited Unmeterd

Following the russian gov decision to steal the Russian Wikipedia and create a censored version and ban the official Wikipedia i also created an onion site for my wikiless instance. You can add it too, if you want:

http://nerdvpnedmmtlnl3uj3xe7dwt6hi52k3lryphmqrxruw6cu2nkddqnid.onion

**Comment by xbdmHQ** [comment]
> URL: https://wiki.nerdvpn.de Hoster: Virtual Systems LLC (vsys.host) Location: Ukraine MITM: No Bot protection: Yes, server-side, no info is shared with third parties Uptime monitor: [Updown.io](https://updown.io/stv1) Server: Dedicated, 2 Gbps Unlimited Unmeterd
> 
> Following the russian gov decision to steal the Russian Wikipedia and create a censored version and ban the official Wikipedia i also created an onion site for my wikiless instance. You can add it too, if you want:
> 
> http://nerdvpnedmmtlnl3uj3xe7dwt6hi52k3lryphmqrxruw6cu2nkddqnid.onion

Added to list!
