### ISSUE TITLE
Add https://wl.zorby.top

### ISSUE THREAD

**Issue by Troughy** [Metastem/wikiless#112]
URL: https://wl.zorby.top
Provider: Pawhost.de
DDoS protection: Provider uses Voxility
Country: Germany

**Comment by Troughy** [comment]
This instance is now available over tor: ztudumrtcreprzdbiq3oadji72hwyftuhk7x3ot7cutgarqfrgcndvad.onion
And also over i2p: jhzwwexyc7vfwz4cau2xaci5znn5e6xmxxosbai6n4nlhv6zl5rq.b32.i2p

**Comment by xbdmHQ** [comment]
> This instance is now available over tor: ztudumrtcreprzdbiq3oadji72hwyftuhk7x3ot7cutgarqfrgcndvad.onion And also over i2p: jhzwwexyc7vfwz4cau2xaci5znn5e6xmxxosbai6n4nlhv6zl5rq.b32.i2p

Added to list.
