### ISSUE TITLE
New instance - https://wl.ca.zorby.top

### ISSUE THREAD

**Issue by Troughy** [Metastem/wikiless#114]
URL: https://wl.ca.zorby.top/
Provider: Servarica.com
CDN/DDoS protection: No
Country: Canada

Tor: http://2duighnva6oizbedfnfiolwh3ed67zedzcdjfzmtnsxlrd2w5jtdxqqd.onion
I2P: http://mdemb7nouujakchiki27qkz53xqhdmmunb7hcnaj2vxfwkmmu5dq.b32.i2p

**Comment by xbdmHQ** [comment]
Instance added to list, sorry for the long wait. The real world is more important than github privacy frontends...
