### ISSUE TITLE
Remove wl.ca.zorby.top

### ISSUE THREAD

**Issue by Troughy** [Metastem/wikiless#116]
Hey, since you locked the issue I can't comment there. I closed that issue for the exact reason you said, real life is more important, therefore I'm gonna stop paying for the Canadian server and it will shut down in 2 days.

**Comment by xbdmHQ** [comment]
> Hey, since you locked the issue I can't comment there. I closed that issue for the exact reason you said, real life is more important, therefore I'm gonna stop paying for the Canadian server and it will shut down in 2 days.

Nah, i didn't mean it like that lol. But whenever you get your life sorted you can make a issue again and ill add the instance. But the instances has been removed! I am going to start my services again very soon, just i don't know when yet.
