### ISSUE TITLE
File Links are formatted incorrectly leading to 404 Errors

### ISSUE THREAD

**Issue by Handrail9** [Metastem/wikiless#117]
When self hosting I've encountered an issue where when visiting a page such as https://en.wikipedia.org/wiki/Internet_Explorer_9, a link to a file on the page like `https://en.wikipedia.org/wiki/File:Internet_Explorer_9_screenshot.png?lang=en` is changed to `https://wikiless.mydomain.tld/File:Internet_Explorer_9_screenshot.png?lang=en` causing a 404 error. It seems for some reason Wikiless is not appending /wiki/ between the domain and /File:. Please let me know if this is a configuration issue or if there's anything else I can do to help. Thanks

**Comment by rufatkiu** [comment]
Everything about link redirection is in routes.js, I'm trying to fix that

**Comment by xbdmHQ** [comment]
> When self hosting I've encountered an issue where when visiting a page such as https://en.wikipedia.org/wiki/Internet_Explorer_9, a link to a file on the page like `https://en.wikipedia.org/wiki/File:Internet_Explorer_9_screenshot.png?lang=en` is changed to `https://wikiless.mydomain.tld/File:Internet_Explorer_9_screenshot.png?lang=en` causing a 404 error. It seems for some reason Wikiless is not appending /wiki/ between the domain and /File:. Please let me know if this is a configuration issue or if there's anything else I can do to help. Thanks

Let us know if the fix worked

**Comment by Handrail9** [comment]
Looks to be fixed now, thanks!
