### ISSUE TITLE
new instance

### ISSUE THREAD

**Issue by GitGitro** [Metastem/wikiless#118]
Hi!

could you add my instance to the wiki whenever you can?

URL: https://wikiless.gitro.xyz
Provider: Hetzner
~~CDN/DDoS protection: Yes~~
CDN/DDoS protection: No
Country: Germany

Thank you!

**Comment by xbdmHQ** [comment]
I will

**Comment by GitGitro** [comment]
just fyi i've edited the issue, i don't use cloudflare anymore

**Comment by xbdmHQ** [comment]
> Germany

Ok, it has been added!
