### ISSUE TITLE
CSS broken solutions

### ISSUE THREAD

**Issue by iamvk1437k** [Metastem/wikiless#15]
![Shot](https://user-images.githubusercontent.com/71950371/221477180-06b7ce8a-0aba-4364-aece-f9fc853eaa42.jpg)

**Comment by Metastem** [comment]
> ![image](https://user-images.githubusercontent.com/75360760/226366346-66e8a003-fa51-4188-81ee-e15dfd53aa2a.png) Seems like a lot of content fails to load. Will this be addressed soon?

Some instances's links in this repo readme are working, you can use their domain

**Comment by iamvk1437k** [comment]
ok Will.

**Comment by iamvk1437k** [comment]
> ok Will.

edit : Ok I Wil.
