### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by eloydegen** [Metastem/wikiless#16]
From mail contact with lawyers from the Wikimedia Foundation, I know that this project is being investigated by them for trademark infringement.

I am not exactly sure what parts are an infringement, but I am pretty sure that using the Wikipedia jigsaw globe logo is an issue. Maybe some links should also be replaced. I'd like to encourage the legal team to specify what parts are problematic so we can fix this issue, before this repository is taken down like the original.

**Comment by xbdmHQ** [comment]
> 

Make a logo for us and we will replace it

**Comment by xbdmHQ** [comment]
> From mail contact with lawyers from the Wikimedia Foundation, I know that this project is being investigated by them for trademark infringement.
> 
> I am not exactly sure what parts are an infringement, but I am pretty sure that using the Wikipedia jigsaw globe logo is an issue. Maybe some links should also be replaced. I'd like to encourage the legal team to specify what parts are problematic so we can fix this issue, before this repository is taken down like the original.

Make a logo for us and we will replace it

**Comment by xbdmHQ** [comment]
@eloydegen

**Comment by xbdmHQ** [comment]
@eloydegen

**Comment by eloydegen** [comment]
What is happening here? Is there some sort of conflict between the maintainers here, or is there now a consensus that this needs to be fixed?
