### ISSUE TITLE
[Feature request] A more rich table layout with sorting.

### ISSUE THREAD

**Issue by Killercat103** [Metastem/wikiless#18]
Is it possible for Wikiless to have a more rich table layout similar the one found in Wikipedia.org?
As you can see table columns are sortable and colorized. Which really helps navigating tables with large amounts of data or when you wish to find rows with certain criteria. As you can see in my example when i sorted in favor of free software
![image](https://user-images.githubusercontent.com/75360760/226920021-222e7cfa-e47d-44ae-a61e-9cd41dc94f58.png)
Wikiless tables are certainly usable (especially with the added benefit of dark mode) but are quite less productive to use.
![image](https://user-images.githubusercontent.com/75360760/226920166-2378c4a5-2dc0-4954-9246-ab777856fa3c.png)

**Comment by xbdmHQ** [comment]
> Is it possible for Wikiless to have a more rich table layout similar the one found in Wikipedia.org? As you can see table columns are sortable and colorized. Which really helps navigating tables with large amounts of data or when you wish to find rows with certain criteria. As you can see in my example when i sorted in favor of free software ![image](https://user-images.githubusercontent.com/75360760/226920021-222e7cfa-e47d-44ae-a61e-9cd41dc94f58.png) Wikiless tables are certainly usable (especially with the added benefit of dark mode) but are quite less productive to use. ![image](https://user-images.githubusercontent.com/75360760/226920166-2378c4a5-2dc0-4954-9246-ab777856fa3c.png)

Wikiless is a privacy frontend of the original Wikipedia page, It isn't a wiki blog page or whatever you're thinking of.

**Comment by Killercat103** [comment]
I'm not sure what wiki blog pages have to do with consitent behavior with the original pagr but ok
