### ISSUE TITLE
SERVER_ERROR_REDIS_SET

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Metastem/wikiless#19]
Hi, after latest update. My instance keep running for a while then errors out with "SERVER_ERROR_REDIS_SET" 

PS: I use docker

**Comment by codedipper** [comment]
**WARNING:** I have barely any experience with Docker, I'm the worst person to try to help.

I experience this error when my server runs out of disk space, any logs?
In line 28 of `docker-compose`, the line:
`- /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev` implies that redis only has 10 MB of disk space.
Try increasing and see what happens?

**Comment by EsmailELBoBDev2** [comment]
> WARNING: I have barely any experience with Docker, I'm the worst person to try to help.

Seems, like me :sweat_smile:. and I tried https://github.com/JarbasAl/wikiless-docker and it works so there is something with redis for sure

**Comment by codedipper** [comment]
> > WARNING: I have barely any experience with Docker, I'm the worst person to try to help.
> 
> Seems, like me sweat_smile. and I tried https://github.com/JarbasAl/wikiless-docker and it works so there is something with redis for sure

Yes, because the hardening was in the latest update which added that suspected disk limit.

**Comment by kuanhulio** [comment]
You can increase the limit or remove the limit entirely.

I should add a HEALTHCHECK to `redis` to see if it's unhealthy and restart that container, thus wiping out the container and restarting, thus making sure it's empty.

**Comment by EsmailELBoBDev2** [comment]
> You can increase the limit or remove the limit entirely.
> 
> For example: removing `read_only` and the `tmpfs` should restore it. Or just remove the size restriction.
> 
> I should add a HEALTHCHECK to `redis` to see if it's unhealthy and restart that container, thus wiping out the container and restarting, thus making sure it's empty.
> 
> @EsmailELBoBDev2 if you can replicate the error and paste it here.

Well, I disabled docker logs for more privacy so can you wait next week when I update instances? I will swap git repos to this one and get the logs

**Comment by kuanhulio** [comment]
Sure, whenever you can get it to me.

In the meantime, you can use the workarounds above, if you'd like.

**Comment by EsmailELBoBDev2** [comment]
Hi, Ok so I updated the server and got back to use this repo and I noticed `read_only` already removed from the docker-compose so i'm just testing now. I will update soon

**Comment by kuanhulio** [comment]
Any log specifically?

**Comment by kuanhulio** [comment]
You can also just remove the `read_only` and `tmpfs` clause

**Comment by EsmailELBoBDev2** [comment]
> You can also just remove the `read_only` and `tmpfs` clause

Yes, from what exactly. I'm a bit confused here :sweat_smile: 

About logs, I will keep it as last resort because I will need to restart whole docker for it. :(

**Comment by kuanhulio** [comment]
From the `redis` part in the compose file.

The reason I'm asking for logs is because I cannot seem to replicate these issues with my config which has these clauses and such.

The error specifically is something I cannot find readily on the internet.

**Comment by EsmailELBoBDev2** [comment]
Oh...I'm dumb. First of all I was using old repo not this one (got distracted with folder names) and I commented tmpfs and read_only lets test if failed I already enabled logs so I will copy and paste it.

**Comment by kuanhulio** [comment]
Just LMK.

**Comment by EsmailELBoBDev2** [comment]
I think we have it!
```yml
redis    | 2023-04-04T19:17:36.190932063Z 1:M 04 Apr 2023 19:17:36.190 # Background saving error
redis    | 2023-04-04T19:17:42.023600075Z 1:M 04 Apr 2023 19:17:42.023 * 1 changes in 3600 seconds. Saving...
redis    | 2023-04-04T19:17:42.023980094Z 1:M 04 Apr 2023 19:17:42.023 * Background saving started by pid 2632
redis    | 2023-04-04T19:17:42.024280062Z 2632:C 04 Apr 2023 19:17:42.024 # Failed opening the temp RDB file temp-2632.rdb (in server root dir /data) for saving: Permission denied
wikiless-web-1 | 2023-04-04T15:21:32.242958649Z Error setting the https://en.wikipedia.org/w/index.php?title=Nintendo_Research_%26_Engineering&mobileaction=toggle_view_mobile key to Redis. Error: ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
wikiless-web-1 | 2023-04-04T15:21:32.365125361Z Fetched url https://en.wikipedia.org/wiki/File:Nintendo_gray_logo.svg?useskin=vector&useskin=vector from Wikipedia.
```
I will mess with the file around and see if i solve it but any recommendations like set it to root or user ?

**Comment by kuanhulio** [comment]
remove the comment on `tmpfs` in redis, and re run it

**Comment by kuanhulio** [comment]
What `tmpfs` does is create a filesystem in memory to which any user should have access to, which is currently set to `nobody`.

`read_only` is set on the redis container because `read_only` doesn't affect `tmpfs` as it's just using memory.

**Comment by EsmailELBoBDev2** [comment]
I removed comment for both and raised redis then if failed again I will do this https://github.com/Metastem/wikiless/issues/19?notification_referrer_id=NT_kwDOAbjiibM1OTU0MTE3MTY4OjI4ODkzODMz#issuecomment-1496799148

**Comment by EsmailELBoBDev2** [comment]
Nope, still have the problem. hmm

**Comment by kuanhulio** [comment]
Well, that's good!

`config set stop-writes-on-bgsave-error no` would probably solve that error in the first part.

**Comment by EsmailELBoBDev2** [comment]
Hmm,
![image](https://user-images.githubusercontent.com/28893833/230251766-a0a12034-59e9-441f-819f-58e282e4584e.png)

```sh
/data# redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

**Comment by kuanhulio** [comment]
not surprising, ill look at this more in depth tomorrow

**Comment by kuanhulio** [comment]
@EsmailELBoBDev2 

Try including the `command` parameter for the `redis` container in compose:

`command: redis-server --stop-writes-on-bgsave-error no`

**Comment by EsmailELBoBDev2** [comment]
Okay, added it and its test time!

worth to mention I found this in logs, it's warning but maybe it's the reason? unsure yet
```sh
WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

**Comment by kuanhulio** [comment]
Memory overcommit is a sysctl on your kernel that you modify. While it's warning you, it shouldn't matter. To get rid of it, you'd need to go to your kernel's sysctl configuration and enable `vm.overcommit_memory=1`.

**Comment by EsmailELBoBDev2** [comment]
oh..kernel? then no :joy:. I'm testing with command option for now and will report later!

**Comment by xbdmHQ** [comment]
@Metastem This issue has been resolved
