### ISSUE TITLE
Link to original Wikipedia Page?

### ISSUE THREAD

**Issue by MintMain21** [Metastem/wikiless#23]
Projects similar to Wikiless (Invidious, Piped, Nitter, BreezeWiki) often feature a handy link to the original link. This is handy not just for sharing the link on social media, but also bookmarking and redirecting in the event of a single instance failing.

Based on both the classic Wikiless design, and the redesign(?) found at wiki.metastem.su, somewhere on the top would be an ideal location for the link. 

Side Tangent, I love the redesign at wiki.metastem.su. I think it could still use some work, but I actually prefer it over both classic Wikiless and the current Wikipedia design. 

PS: In general I really like the design of BreezeWiki if you wanted some additional inspiration.

**Comment by xbdmHQ** [comment]
Make a pull request and contribute
