### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [Metastem/wikiless#29]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `wikiless.esmailelbob.xyz` / `wikiless.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by Metastem** [comment]
> Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*. This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `wikiless.esmailelbob.xyz` / `wikiless.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.
> 
> *See the commit here: [EsmailELBoBDev2/upptime@c46b9bf](https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a)

Seems right, they are. I'm looking into it and taking actions soon
BTW, Metastem is an ultra left anarcho communists'  organisation, but we still pay respect to very little parts of libertarian, but fascists will never get one of their seats here.

**Comment by tiekoetter** [comment]
I don't understand why one would even write this into their TOS...

This person is also hosting other FOSS instances maybe the people maintaining these lists should also be informed about their TOS.

**Comment by MagicLike** [comment]
> I don't understand why one would even write this into their TOS...
> 
> This person is also hosting other FOSS instances maybe the people maintaining these lists should also be informed about their TOS.

Already done :+1:

**Comment by tiekoetter** [comment]
@MagicLike They also host a SearXNG instance. If you would be so kind and open an issue in https://github.com/searxng/searx-instances/issues

I will discuss this with the team when you have done this. I will remove the instance from the list when the majority of the team agrees.

**Comment by MagicLike** [comment]
> @MagicLike They also host a SearXNG instance. If you would be so kind and open an issue in https://github.com/searxng/searx-instances/issues
> 
> I will discuss this with the team when you have done this. I will remove the instance from the list when the majority of the team agrees.

Done, see https://github.com/searxng/searx-instances/issues/344

**Comment by Metastem** [comment]
This instance has been deleted.
