### ISSUE TITLE
Mark privacy-unfriendly instance(s)

### ISSUE THREAD

**Issue by honobo** [Metastem/wikiless#72]
It's disturbing that the official instance https://wikiless.whateveritworks.org/ is blocking Tor. Such a privacy-unfriendly, Tor-censoring instance should be clearly marked as scuh, as Tor users assume that privacy-friendly services are almost always Tor-friendly, and as such, when you block Tor, you'll potentially lose credibility. If warned in advance (that Tor is not supported on that instance), this rude shock would be somewhat mitigated, even though privacy-oriented users might prefer another option (e.g. metager), once they realize wikiless is not really serious - not trying to help Tor users (some of whom can view the Internet freely only thanks to Tor, Snowflakes etc).

**Comment by xbdmHQ** [comment]
> 

Then you made a GitHub account which logs your IP address constantly, so saying your on tor 24/7 is cap.

**Comment by xbdmHQ** [comment]
> It's disturbing that the official instance https://wikiless.whateveritworks.org/ is blocking Tor. Such a privacy-unfriendly, Tor-censoring instance should be clearly marked as scuh, as Tor users assume that privacy-friendly services are almost always Tor-friendly, and as such, when you block Tor, you'll potentially lose credibility. If warned in advance (that Tor is not supported on that instance), this rude shock would be somewhat mitigated, even though privacy-oriented users might prefer another option (e.g. metager), once they realize wikiless is not really serious - not trying to help Tor users (some of whom can view the Internet freely only thanks to Tor, Snowflakes etc).


Then you made a GitHub account which logs your IP address constantly, so saying your on tor 24/7 is cap.

**Comment by honobo** [comment]
Thank you very much. Maybe it's just that your threat model is a bit diffent than that of a typical privacy-oriented community. I'm sorry if pointing out that somehow upset you.

I essentially think this project is great and insightful :)  at least partially, and I do respect your decision. I could even make a donation to support the project if you could speak civilly and think rationally, instead of using strong language needlessly. I simply meant that: It would be more helpful if the instance list were transparent. You can block Tor if you'd like to, but it's more convenient for end users if you disclose that fact.

Sadly, privacy-aware users (like you) are still minority. So they (we) tend to try to help each other, as we should, rather than arguing emotionally. We'd like to be transparent; we tend to say, freely, that it's disturbing if something is disturbing, or we frankly say e.g. "Don't use Google Font" "Try to be more Tor-friendly". It's nothing personal. I hope you'll understand this point...
While Github is so-far rather Tor-friendly, you're absolutely right. Quite a few privacy-aware projects avoid Github, e.g. self-hosting Gitlab or using codeberg. Github had even banned Tornado Cash, which is much more disturbing tbh. Also, devs of popular privacy front-ends (e.g. Teddit and Invidious) obviously assume that JavaScript is disabled by default.
Although those things are very important too (since Wikipedia tries to set so many tracking cookies), such a behavior of WP can be prevented trivially by just disabling cookies, and that has nothing to do with you blocking Tor, especially when Wikipedia itself doesn't block Tor. Obviously I've never signed up nor logged in to Github or whatever without Tor/VPN; my email address they have is itself anonymously created and only used via Tor/VPN. Every cookie someone sets will be "amnestic" as in Tails, if that is what you're talking about... Although, that has nothing to do with this issue.

It's not like I took time to write my comments because I personally hate you. Nevertheless, again, I'm really sorry if you felt that way.

**Comment by xbdmHQ** [comment]
> Thank you very much. Maybe it's just that your threat model is a bit diffent than that of a typical privacy-oriented community. I'm sorry if pointing out that somehow upset you.
> 
> I essentially think this project is great and insightful :) at least partially, and I do respect your decision. I could even make a donation to support the project if you could speak civilly and think rationally, instead of using strong language needlessly. I simply meant that: It would be more helpful if the instance list were transparent. You can block Tor if you'd like to, but it's more convenient for end users if you disclose that fact.
> 
> Sadly, privacy-aware users (like you) are still minority. So they (we) tend to try to help each other, as we should, rather than arguing emotionally. We'd like to be transparent; we tend to say, freely, that it's disturbing if something is disturbing, or we frankly say e.g. "Don't use Google Font" "Try to be more Tor-friendly". It's nothing personal. I hope you'll understand this point... While Github is so-far rather Tor-friendly, you're absolutely right. Quite a few privacy-aware projects avoid Github, e.g. self-hosting Gitlab or using codeberg. Github had even banned Tornado Cash, which is much more disturbing tbh. Also, devs of popular privacy front-ends (e.g. Teddit and Invidious) obviously assume that JavaScript is disabled by default. Although those things are very important too (since Wikipedia tries to set so many tracking cookies), such a behavior of WP can be prevented trivially by just disabling cookies, and that has nothing to do with you blocking Tor, especially when Wikipedia itself doesn't block Tor. Obviously I've never signed up nor logged in to Github or whatever without Tor/VPN; my email address they have is itself anonymously created and only used via Tor/VPN. Every cookie someone sets will be "amnestic" as in Tails, if that is what you're talking about... Although, that has nothing to do with this issue.
> 
> It's not like I took time to write my comments because I personally hate you. Nevertheless, again, I'm really sorry if you felt that way.

The issue has been resolved for now, If i see any threats taken with tor traffic it will be blocked again.
