### ISSUE TITLE
invalid lang error

### ISSUE THREAD

**Issue by nihilist001** [Metastem/wikiless#75]
Hello,

as seen on https://wikiless.datura.network/ i get the error "invalid lang" even though i put 'en' as the language.

current files:

-docker-compose.yml: https://privatebin.nihilism.network/?2c50d36283da2f67#3nKhFrJHDUpe8VmCtYmp5G8ZHb1r4XMytnfdVuN8zuKw

-wikiless.config: https://privatebin.nihilism.network/?4ce8268ce094847a#DsCCUR8pAEREAgUrZ4GgSSL4bGaVQBw3jwozJKQqr5Wo

-nginx reverse proxy site config: https://privatebin.nihilism.network/?c80d9878ed9ebe28#HZv5DxEr8PftrsqjndFRVkKMnRMppyfGt1ZpaeGKub8J 

any idea what i did wrong there ?

**Comment by xbdmHQ** [comment]
> Hello,
> 
> as seen on https://wikiless.datura.network/ i get the error "invalid lang" even though i put 'en' as the language.
> 
> current files:
> 
> -docker-compose.yml: https://privatebin.nihilism.network/?2c50d36283da2f67#3nKhFrJHDUpe8VmCtYmp5G8ZHb1r4XMytnfdVuN8zuKw
> 
> -wikiless.config: https://privatebin.nihilism.network/?4ce8268ce094847a#DsCCUR8pAEREAgUrZ4GgSSL4bGaVQBw3jwozJKQqr5Wo
> 
> -nginx reverse proxy site config: https://privatebin.nihilism.network/?c80d9878ed9ebe28#HZv5DxEr8PftrsqjndFRVkKMnRMppyfGt1ZpaeGKub8J
> 
> any idea what i did wrong there ?

Try to remove this from your nginx:
```
######## TOR CHANGES ########
    listen 4443;
    listen [::]:4443;
    server_name wikiless.daturab6drmkhyeia4ch5gvfc2f3wgo6bhjrv3pz6n7kxmvoznlkq4yd.onion;
    add_header Onion-Location "http://wikiless.daturab6drmkhyeia4ch5gvfc2f3wgo6bhjrv3pz6n7kxmvoznlkq4yd.onion/$request_uri" always;
    ######## TOR CHANGES ########
```
and do ```sudo systemctl reload nginx``` to test the changes also do ```sudo nginx -t```

**Comment by xbdmHQ** [comment]
Also make sure to not add, ```add_header Onion-Location``` this is a security issue to deanonymized tor users. 
https://sh1ttykids.medium.com/new-techniques-uncovering-tor-hidden-service-with-etag-5249044a0e9d

**Comment by xbdmHQ** [comment]
@nihilist001

**Comment by nihilist001** [comment]
Hi, pasting here:

as seen on https://wikiless.datura.network/ i get the error "invalid lang" even though i put 'en' as the language.

current files:

-docker-compose.yml: https://privatebin.nihilism.network/?de4d85add74740d3#H6jW6hVncNEjHSwXVjkQUt3H6cuWdrsjmwgBszoZT446

-wikiless.config: https://privatebin.nihilism.network/?9d16b41b278d2416#Bu77KAgyrcUjGcGAtDXavZT8pReDNFN3GZD79A5kjVtQ

(new since last issue: removed the onion headers)-nginx reverse proxy site config: https://privatebin.nihilism.network/?ddf8831f6377d299#4xr3k2DKxtT4EeWMw9Awiac3sKpNQJVEC164awA3dBQn

(new since last issue): testing the webserver without going through the nginx reverse proxy: https://privatebin.nihilism.network/?a023c303685ab320#BGTafV1wR4R5Mdyp529doPkKKUGXU9GX6K2ECQx9LN3P

not sure that it would be the reverse nginx proxy being the issue since when testing directly without going through nginx i still get the invalid lang error.

What are the valid values for the lang parameter in the wikiless.config file ?

also letting you know where are each file: https://privatebin.nihilism.network/?0f2a9debc6015e79#47412nt3Vfvi8cKjtHdVGdysZLdNMZgF6ZcR43BpkMzh

**Comment by xbdmHQ** [comment]
> Hi, pasting here:
> 
> as seen on https://wikiless.datura.network/ i get the error "invalid lang" even though i put 'en' as the language.
> 
> current files:
> 
> -docker-compose.yml: https://privatebin.nihilism.network/?de4d85add74740d3#H6jW6hVncNEjHSwXVjkQUt3H6cuWdrsjmwgBszoZT446
> 
> -wikiless.config: https://privatebin.nihilism.network/?9d16b41b278d2416#Bu77KAgyrcUjGcGAtDXavZT8pReDNFN3GZD79A5kjVtQ
> 
> (new since last issue: removed the onion headers)-nginx reverse proxy site config: https://privatebin.nihilism.network/?ddf8831f6377d299#4xr3k2DKxtT4EeWMw9Awiac3sKpNQJVEC164awA3dBQn
> 
> (new since last issue): testing the webserver without going through the nginx reverse proxy: https://privatebin.nihilism.network/?a023c303685ab320#BGTafV1wR4R5Mdyp529doPkKKUGXU9GX6K2ECQx9LN3P
> 
> not sure that it would be the reverse nginx proxy being the issue since when testing directly without going through nginx i still get the invalid lang error.
> 
> What are the valid values for the lang parameter in the wikiless.config file ?
> 
> also letting you know where are each file: https://privatebin.nihilism.network/?0f2a9debc6015e79#47412nt3Vfvi8cKjtHdVGdysZLdNMZgF6ZcR43BpkMzh

Don't use the image, build from source instead!

**Comment by nihilist001** [comment]
yep that was it, thanks for the help!
i'll release a tutorial to set it up soon at https://blog.nihilism.network/servers/wikiless/index.html

**Comment by xbdmHQ** [comment]
> yep that was it, thanks for the help! i'll release a tutorial to set it up soon at https://blog.nihilism.network/servers/wikiless/index.html

Yeah, that was metastem package, i do not run a image. But i prefer to run it build from source for more security than on a cloud like dockerhub or etc. But glad it worked, adding your instance to the list.
