### ISSUE TITLE
got v13 does not support CommonJS export

### ISSUE THREAD

**Issue by codedipper** [Metastem/wikiless#81]
```sh
$ npm start

> Wikiless@0.1.1 start
> node src/wikiless.js

/home/node/wikiless/src/utils.js:7
  const got = require('got')
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/node/wikiless/node_modules/got/dist/source/index.js from /home/node/wikiless/src/utils.js not supported.
Instead change the require of index.js in /home/node/wikiless/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports (/home/node/wikiless/src/utils.js:7:15)
    at Object.<anonymous> (/home/node/wikiless/src/wikiless.js:28:36) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.0
```

Also, I manually added the entries for `express-session` and `lusca` in package.json because otherwise they won't install with npm install

**Comment by xbdmHQ** [comment]
> ```shell
> $ npm start
> 
> > Wikiless@0.1.1 start
> > node src/wikiless.js
> 
> /home/node/wikiless/src/utils.js:7
>   const got = require('got')
>               ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/node/wikiless/node_modules/got/dist/source/index.js from /home/node/wikiless/src/utils.js not supported.
> Instead change the require of index.js in /home/node/wikiless/src/utils.js to a dynamic import() which is available in all CommonJS modules.
>     at module.exports (/home/node/wikiless/src/utils.js:7:15)
>     at Object.<anonymous> (/home/node/wikiless/src/wikiless.js:28:36) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> Node.js v18.17.0
> ```
> 
> Also, I manually added the entries for `express-session` and `lusca` in package.json because otherwise they won't install with npm install

Thank i forgot to add those in the package.json.

**Comment by xbdmHQ** [comment]
> ```shell
> $ npm start
> 
> > Wikiless@0.1.1 start
> > node src/wikiless.js
> 
> /home/node/wikiless/src/utils.js:7
>   const got = require('got')
>               ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/node/wikiless/node_modules/got/dist/source/index.js from /home/node/wikiless/src/utils.js not supported.
> Instead change the require of index.js in /home/node/wikiless/src/utils.js to a dynamic import() which is available in all CommonJS modules.
>     at module.exports (/home/node/wikiless/src/utils.js:7:15)
>     at Object.<anonymous> (/home/node/wikiless/src/wikiless.js:28:36) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> Node.js v18.17.0
> ```
> 
> Also, I manually added the entries for `express-session` and `lusca` in package.json because otherwise they won't install with npm install

Ah oh ok, I found the issue.

```
Wed, 02 Aug 2023 19:56:37 GMT express-session deprecated undefined resave option; provide resave option at src/wikiless.js:91:9
Wed, 02 Aug 2023 19:56:37 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at src/wikiless.js:91:9
Wed, 02 Aug 2023 19:56:37 GMT express-session deprecated req.secret; provide secret option at src/wikiless.js:91:9
```
