### ISSUE TITLE
French wiki pages have broken layouts

### ISSUE THREAD

**Issue by Cwpute** [Metastem/wikiless#85]
_EDIT: this is a bigger issue than i thought, as it doesn't only concern pages generated from search results, but all french wiki pages. i edited this issue to reflect my findings._

Many Wikipedia pages from the french Wikipedia have a broken layout.
Here are some examples i found:

## Pages from search results
I use the Wikipedia search engine to search for terms directly in my web-browser (Firefox).
![image](https://github.com/Metastem/wikiless/assets/80604512/f5cb4566-f8f2-4107-b315-846c9b1f9e80)

In my example, i'll consistently use `wl.vern.cc` as my instance, and the term `bouvier` for my search on the french wiki pages.

If the term i'm searching for directly links to an existing page, that page will have its layout broken, like shown below. In my example, the page link is the following: `https://wl.vern.cc/wiki/Sp%C3%A9cial:Recherche?search=bouvier&sourceid=Mozilla-search&lang=fr` 
![image](https://github.com/Metastem/wikiless/assets/80604512/2d586df1-483d-4195-903a-d0d0d023fe2f)

But if i access the same page from somewhere else on the instance, as you can see below, the page looks like normal. The link to this page is different: `https://wl.vern.cc/wiki/Bouvier?lang=fr`
![image](https://github.com/Metastem/wikiless/assets/80604512/1d59dc1a-3303-4c83-9fcf-dcbfe3e3abc6)

Maybe wikiless can convert the search link to a regular link instead. I don't think the info passed down through the search result link is important to wikiless or the instance through which it passes.

## Navigation menu
_copied from https://github.com/Metastem/wikiless/issues/86_

![image](https://github.com/Metastem/wikiless/assets/80604512/1b897d0c-bf5d-4454-8ddd-3418c6f0cdf3)
On wiki pages, the Navigation menu that should be on the side of the screen is located at the bottom instead.
At first i thought making the navigation menu disappear was a educated decision, but apparently it's not !

This was experienced on the `wl.vern.cc` instance.

## Other stuff probably ?
These are some observations i could make, but i guess more layout problems might exist. It might be worth checking other languages to see if their pages are broken too.

If accounting for any other languages than english is too hard, maybe then display a warning message explaining wikiless doesn't currently fully support pages for languages other than english, with an option to redirect to the official Wikipedia page, or the equivalent english page on Wikiless.

**Comment by xbdmHQ** [comment]
This issue has already been resolved, Use a updated instance instead! wikiless.whateveritworks.org

**Comment by Cwpute** [comment]
i've asked the vern.cc admins to update their instance. I guess this issue can be closed now ?
