### ISSUE TITLE
Issue with URL redirection

### ISSUE THREAD

**Issue by unstablemaple** [Metastem/wikiless#92]
I am trying to host a public instance for wikiless, however for each link that I click it returns `CANNOT GET <topic>`  . I have tried redirecting `https://wiki.example.com` to `https://wiki.example.com/` using NGINX but then nothing seems to function properly. NGINX serves the instance as it supposed to but links and other CSS elements don't load. Any idea how to fix this?

**Comment by hyperreal64** [comment]
Same issue here.

**Comment by hyperreal64** [comment]
> I am trying to host a public instance for wikiless, however for each link that I click it returns `CANNOT GET <topic>` . I have tried redirecting `https://wiki.example.com` to `https://wiki.example.com/` using NGINX but then nothing seems to function properly. NGINX serves the instance as it supposed to but links and other CSS elements don't load. Any idea how to fix this?

I got it working. I edited wikiless.config to use my domain (without the https://). Then I removed the images that were built, because those images were using the old wikiless.config. I ran podman-compose again, which rebuilt the images and created containers with the new config. This seems to have done the trick.

If you're using Docker, the commands are the same, but you replace "podman-" with "docker-".

Stop the wikiless instance:
`podman-compose down`

Remove the image that was built previously:
`podman rmi localhost/wikiless_wikiless`

Run the compose command again:
`podman-compose up -d`

The wikiless image will be rebuilt with the new config.

**Comment by unstablemaple** [comment]
@hyperreal64 It's still not working, it loads a static page and the CSS elements aren't working properly.

**Comment by hyperreal64** [comment]
> @hyperreal64 It's still not working, it loads a static page and the CSS elements aren't working properly.

Can you provide a screen shot?

I have noticed that the CSS is messed up when using the dark theme on some instances. My instance does not have this issue. Does this issue happen for you on a specific theme, or all of them?

**Comment by unstablemaple** [comment]
@hyperreal64 Surely,
![image](https://github.com/Metastem/wikiless/assets/145098674/3fa42467-112a-4dea-9b18-c793fc94184d)
And this is what I get in the console: 

```wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.
wikiless    | Got key https://en.wikipedia.org/?useskin=vector&useskin=vector from cache.```

**Comment by hyperreal64** [comment]
I don't see anything wrong in the screenshot. Can you paste your wikiless.config (removing secret information)?
