### ISSUE TITLE
Question about wiki.metastem.su skin

### ISSUE THREAD

**Issue by iSack97** [Metastem/wikiless#93]
Hello
I know wiki.metastem.su is using minimalpedia skin, but can somebody describe how I can use this skin with wikiless on my own instance?
I am using docker btw.

**Comment by iSack97** [comment]
@xbdmHQ can you please tell me how to change the skin on a wikiless instance? Or tell me who i can ask…
There is almost no documentation

**Comment by xbdmHQ** [comment]
> @xbdmHQ can you please tell me how to change the skin on a wikiless instance? Or tell me who i can ask… There is almost no documentation

Metasteam isn't wikiless, it's his version of wikipedia. You have to email him about that, I just maintain wikiless on my free time...
