### ISSUE TITLE
My instance is up!

### ISSUE THREAD

**Issue by unstablemaple** [Metastem/wikiless#94]
Instance: [wiki.seitan-ayoub.lol](https://wiki.seitan-ayoub.lol)
Location: Germany
Cloudflare: no

**Comment by xbdmHQ** [comment]
> Instance: [wiki.seitan-ayoub.lol](https://wiki.seitan-ayoub.lol)
> 
> Location: Germany
> 
> Cloudflare: no

Thank you for hosting a instance, I will add it to the list when I get a chance.
